### ISSUE TITLE
Can not access post data

### ISSUE THREAD

**Issue by iamchathu** [ivantcholakov/codeigniter-restserver-test#1]
can not get post data from $this->post('key') 

Im using php 5.3

**Comment by ivantcholakov** [comment]
If the original project https://github.com/chriskacerguis/codeigniter-restserver has a bug, report it there.

**Comment by ivantcholakov** [comment]
@iamchathu

Within application/controllers/api/Example.php there is a controller serving a POST request:

``` php
    public function users_post()
    {
        // $this->some_model->update_user( ... );
        $message = array(
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        );

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
```

I have just added a test for it, release 2.7.2.37.
Here is a live demo: http://iridadesign.com/codeigniter-restserver-test/post-test

From what I can see, $this->post('name') and $this->post('email') work.
