### ISSUE TITLE
minor array declaration error in Example.php

### ISSUE THREAD

**Issue by pchambeth** [ivantcholakov/codeigniter-restserver-test#2]
The hobbies key has an extra bracket around it. i believe it should be
'hobbies' => ['guitar', 'cycling']

instead of

['hobbies' => ['guitar', 'cycling']]

**Comment by ivantcholakov** [comment]
It could be correct in both cases, it is matter of developer's choice how data to be structured. For now I intend to keep this fragment of code as it is in the original project. Thank you for pointing about that.
